### ISSUE TITLE
I only see the border of the view..

### ISSUE THREAD

**Issue by ameliandev** [vinnyoodles/DualSlideMenu#11]
Hi. 

I'm triying to implement your Menu in my project. I'm following the example that do you have in the specifications, all works fine, but when I swipe the Main view, I only see a minimal border of the left view. I don't know if I put some extra to see the entire view.

See the atached image:
![menu](https://cloud.githubusercontent.com/assets/5382347/16730647/08d49358-476c-11e6-9dc7-3a909d0ec22b.png)

Can you help me?

Regards,

**Comment by vincent144** [comment]
Could you post a code snippet of how you are setting up the view hierarchy?

**Comment by ameliandev** [comment]
Yes sure. This is my AppDelegate content. Of course, the left View exists ("leftMenuViewController")

`import UIKit
import DualSlideMenu

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

```
var window: UIWindow?
var storyBoard: UIStoryboard?


func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
    // Override point for customization after application launch.

    window = UIWindow(frame: UIScreen.mainScreen().bounds)
    storyBoard = UIStoryboard(name: "Main", bundle: nil)

    let lLeft = storyBoard?.instantiateViewControllerWithIdentifier("appMenuLeftCtrl") as! MenuLeftController
    let lMain = storyBoard?.instantiateViewControllerWithIdentifier("MainCtrl")

    let controller = DualSlideMenuViewController(mainViewController: lMain!, leftMenuViewController: lLeft)

    controller.leftSideOffset = 100
    window!.rootViewController = controller
    window!.makeKeyAndVisible()

    return true
}
```

}`

**Comment by vincent144** [comment]
That looks good. The only thing I can think of that may be the storyboard. Did you add any views or constraints in the `MenuLeftController`?

**Comment by ameliandev** [comment]
No, nothing. The scene contains a View without controls or constraints, only a grey background.

**Comment by vincent144** [comment]
<img width="372" alt="screenshot-1" src="https://cloud.githubusercontent.com/assets/8698599/16734196/a3d68902-4752-11e6-9e6f-e9b6ca5bd041.png">

Use this tool and see what is happening to the left view. This might help https://www.raywenderlich.com/98356/view-debugging-in-xcode-6

**Comment by ameliandev** [comment]
Well, in the debug view I see the content...maybe it's emulator problem?? I'm running it on iPhone 6 simulator with 9.1 ios

**Comment by vincent144** [comment]
hmm, that's weird. I guess it must be an emulator problem, but I'm not sure how it could...

**Comment by ameliandev** [comment]
Solved..this my fault. I had using a background that cover the view

**Comment by vincent144** [comment]
Awesome, hope I was some help to you and thanks for using my library :)
